name: Docker

on:
  push:
    paths:
      - 'src/components/**'

  pull_request:
    branches: [ main ]

jobs:
    deploy:
        
        name: Docker Build and push to Google CLoud Run
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/fintech-devops
        steps:
      
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT }}
            service_account_email: ${{ secrets.GCP_SERVICE_EMAIL }}
            service_account_key: ${{ secrets.GCP_CR_SA_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Add in Auth0 Credential
          run: jq '.domain = $d | .clientId = $c | .audience = $a' src/auth_config.json --arg a "$AUDIENCE" --arg c "$CLIENTID" --arg d "$DOMAIN"
          env:
            AUDIENCE: ${{ secrets.AUDIENCE }}
            DOMAIN: ${{ secrets.DOMAIN }}
            CLIENTID: ${{ secrets.CLIENTID }} 
          

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy grabbuddy-devops ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region asia-southeast1 --platform managed
