name: Grab-Buddy CI

on:
  push:
    paths:
      - 'src/components/**'

  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install jq
        run: sudo apt-get install jq
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        env:
          AUDIENCE: ${{ secrets.AUDIENCE }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          CI : false
      - name: Add in Auth0 Credential
        run: echo "`jq '.domain="$DOMAIN"' | clientId = "$CLIENTID" | .audience = "$AUDIENCE"' src/auth_config.json `" > src/auth_config.json
        env:
          AUDIENCE: ${{ secrets.AUDIENCE }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{secrets.GCP_SA_KEY}}

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: v1
