name: Grab-Buddy CI

on:
  push:
    paths:
      - 'src/components/**'

  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install moreutil for linux
        run: sudo apt-get install moreutils
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        env:
          AUDIENCE: ${{ secrets.AUDIENCE }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CLIENTID: ${{ secrets.CLIENTID }}
          CI : false
      - name: Add in Auth0 Credential
        run: jq --arg a "$AUDIENCE" --arg c "$CLIENTID" --arg d "$DOMAIN" '.domain = $d | .clientId = $c | .audience = $a' src/auth_config.json|sponge src/auth_config.json 
        env:
          AUDIENCE: ${{ secrets.AUDIENCE }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CLIENTID: ${{ secrets.CLIENTID }}
      - name: Set Auth0 Domain 
        uses: jossef/action-set-json-field@v1
        with: 
          file: src/auth_config.json
          field: domain
          value: ${{ secrets.DOMAIN }}
        
      - name: Set Auth0 ClientID 
        uses: jossef/action-set-json-field@v1
        with: 
          file: src/auth_config.json
          field: clientId
          value: ${{ secrets.CLIENTID }}


      - name: Set Auth0 Audience 
        uses: jossef/action-set-json-field@v1
        with: 
          file: src/auth_config.json
          field: audience
          value: ${{ secrets.AUDIENCE }}
      

          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{secrets.GCP_SA_KEY}}

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: v1
